#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

APP_HOME=$( cd "$( dirname "$0" )" && pwd )
APP_NAME="Gradle"
APP_BASE_NAME=$( basename "$0" )

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -z "$JAVA_EXE" ] || [ ! -x "$JAVA_EXE" ]; then
    JAVA_EXE=java
fi

set -- \
        "-classpath" "$CLASSPATH" \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

exec "$JAVA_EXE" "$@"
